# Configuration du Config Server
spring.application.name=gateway
spring.config.import=optional:configserver:http://localhost:8888
spring.cloud.config.enabled=true
spring.cloud.config.import-check.enabled=true

server.port=8065

# Le reste de la configuration est centralisé dans le config-server